### ISSUE TITLE
Installation instructions wrong

### ISSUE THREAD

**Issue by redskyburning** [harm-less/angular-sticky#3]
Hey, the library looks great, but I've been having a lot of trouble getting things working due to inaccurate docs. The bower install line should be `bower install angular-sticky-plugin`, currently it points to a totally different library. Also, to include it in the project it appears to be `hl-sticky` rather than `hl.sticky`. Finally, https://github.com/jonathantneal/angular-sticky shares the same name, which makes googling for this lib tricky. Not sure what you can do about that really, but FYI.

**Comment by harm-less** [comment]
Hey, thanks for the effort of figuring this out and posting your findings.

You're right about the bower install instructions. It appears I had forgotten to update this. I'll take at look at this tonight and update them.
The ```hl.sticky``` module name should be correct. I checked the source from 0.1.0. Are you sure you're using that version?

And about the name, I struggled with it a lot. Every normal name was taken and Angular Sticky is what it is. So although the name doesn't match up in Bower, I just went with it.

The plugin is still under heavy development because it's quite new, so I'm still trying to work out the best approach on how to handle certain things. I think in a month or 2 I'll have a 1.0.0 version ready. I don't think the API will change very much anymore though.

**Comment by redskyburning** [comment]
Thanks for the quick reply, I saw you already fixed the bower line. I just retested hl.sticky vs hl-sticky and using hl.sticky throws the following error (testing in chrome) : 

`angular.js:68 Uncaught Error: [$injector:modulerr] Failed to instantiate module frodo due to:
Error: [$injector:modulerr] Failed to instantiate module hl.sticky due to:
Error: [$injector:nomod] Module 'hl.sticky' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.`

Switching to hl-sticky removes the error. Looking in angular-sticky.js the module is defined as 'hl-sticky'.  Bower claims I'm using v 1.0.1, which doesn't make much sense if you're working on 0.1.0. I see this version on CLI when installing and looking at the bower.json bower_components/angular-sticky/. Not sure what's going on, I'm starting to suspect some bower weirdness.

I'm going to keep playing with it today and see if I can actually get it running within my app, will give you feedback when I do.

**Comment by redskyburning** [comment]
Cloned the repo directly, and it's very different from what is on bower. Locally I now see `hl.sticky` and the version is listed as 0.1.0.

**Comment by harm-less** [comment]
I did fix fix the bower line, I'll update the demo page soon as well. I've been trying to implement a few features that aren't quite ready yet.

And I must admit I had been playing with version numbers a few weeks back, but I find it hard to imagine you've only had this problem just now... Though, that's the only thing I could think of that would cause your problem.

**Comment by harm-less** [comment]
I just saw a release called ```1.0.1``` which was an old one (I went back to a ```0.*.*``` release as I don't feel like the project ready for production just yet). I've deleted it now, but I think it was what caused your problem.

P.s.: I just made another (pre)release and the demo is updated in the process. The demo page has the correct installation instructions too.
